#!/usr/bin/env bash
# This script checks DNS A records of subdomains for a given domain

function check_subdomain {
  local domain=$1
  local subdomain=$2
  result=$(dig ${subdomain}.${domain} +short)
  if [ -n "$result" ]; then
    echo "The subdomain ${subdomain} is a A record and points to ${result}"
  fi
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  for sd in www lb-01 web-01 web-02; do
    check_subdomain $domain $sd
  done
else
  check_subdomain $domain $subdomain
fi
