#!/usr/bin/env bash
# Installs and configures Nginx web server

apt-get update
apt-get install -y nginx

# Create HTML file with Hello World!
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx
service nginx restart