#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

# Create custom 404 page
mkdir -p /var/www/html/error_pages
echo "Ceci n'est pas une page" > /var/www/html/error_pages/404.html

# Update Nginx configuration
error_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    error_page 404 /error_pages/404.html;
    location = /error_pages/404.html {
        root /var/www/html;
        internal;
    }
    
    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}"

echo "$error_config" > /etc/nginx/sites-available/default

# Test configuration and restart Nginx
nginx -t
service nginx restart