#!/usr/bin/env bash
# Configures port forwarding from 8080 to 80 using UFW

# Enable IP forwarding
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sysctl -p

# Configure UFW to allow port 8080
ufw allow 8080/tcp

# Set up port forwarding rules
ufw route allow proto tcp from any to any port 80

# Add NAT rule for port forwarding
echo -e "*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT" >> /etc/ufw/before.rules

# Restart UFW to apply changes
ufw disable
ufw enable